name = "CliffordDynamics"
uuid = "8c9896b1-975b-40a4-9a39-405887a18a22"
authors = ["Bianca Bannenberg <bbannenberg@gmx.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
