name = "CliffordDynamics"
uuid = "8c9896b1-975b-40a4-9a39-405887a18a22"
authors = ["Bianca Bannenberg <bbannenberg@gmx.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"

[compat]
Distributions = "0.25.120"
LinearAlgebra = "1.11.0"
QuantumClifford = "0.9.19"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
